version: '3'

services:
  db:
    container_name: "test_db2"
    
    build:
      context: .
      dockerfile: ./backend/db.dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "tareas2"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "Argentina.123"
      
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    
  api:
    container_name:  "test_api2"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8087:80"
    depends_on:
      - db
    volumes:
      - .:/app/

networks:
  default:
volumes:
  mysql_data: